In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
%matplotlib inline

In [5]:
from sklearn import metrics

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
from sklearn.linear_model import LogisticRegression

In [9]:
from sklearn.model_selection import train_test_split

In [12]:
# Load the dataset
df=pd.read_csv('portals.csv')

In [13]:
df

,name,title,url,author,publisher,issued,publisher_classification,description,tags,license_id,...,place,location,country,language,status,metadatacreated,generator,api_endpoint,api_type,full_metadata_download
0,a2gov_org,"Ann Arbor, Michigan",http://www.a2gov.org/services/data/Pages/defau...,City of Ann Arbor,City of Ann Arbor,NaN,NaN,City of Ann Arbor's Open Data Catalog (USA),ctic unitedstates,NaN,...,"Ann Arbor, Michigan","42.2681569,-83.7312291",US,en,active,2011-06-27T18:12:57.439Z,NaN,Not apparent,NaN,NaN
1,acikveri-sahinbey-bel-tr,Açık Veri Portali - Test Yayını,http://acikveri.sahinbey.bel.tr/dataset,pinardag,SahinBey Belediyesi,31/01/2015,Government,The first official open data portal of Turkey,turkey national,Unknown,...,"Gaziantep,Turkey","37.0587715,37.380137",TR,tr,active,NaN,NaN,NaN,NaN,NaN
2,africa_open_data,Africa Open Data,http://africaopendata.org/,Africa Open Data,Africa Open Data,NaN,NaN,Africa's largest central repository for Govern...,ckan africa,NaN,...,Africa,"2.0000003,15.9999997",AF,en,active,2013-03-15T07:17:26.251Z,CKAN: 2.1.3,http://africaopendata.org/api/,NaN,NaN
3,ajuntament-de-tarragona,Open Data Tarragona,http://opendata.tarragona.cat/,Ajuntament de Tarragona,Ajuntament de Tarragona,NaN,Government,Open Data Tarragona,city spain,NaN,...,Tarragona,"41.1157, 1.2496",ES,ca es en,active,NaN,NaN,NaN,NaN,NaN
4,ajuntament-de-terassa,Open Data Terassa,http://opendata.terrassa.cat/,Ajuntament de Terassa,Ajuntament de Terassa,NaN,Government,Open Data Terassa,city spain,NaN,...,Terrasa,"41.5611, 2.0081",ES,es en,active,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,state_of_washington,Washington,http://geo.wa.gov,State of Washington,State of Washington,NaN,Government,Geospatial open data from the State of Washington,unitedstates,NaN,...,"Washington, United States","47.034922, -122.895756",US,en,active,NaN,NaN,NaN,Esri ArcGIS Online,NaN
590,state_of_washington,Washington,http://fiscal.wa.gov,State of Washington,State of Washington,NaN,Government,Fiscal open data for state of Washington,finance unitedstates,NaN,...,"Washington, United States","47.034922, -122.895756",US,en,active,NaN,NaN,NaN,NaN,NaN
591,portal-de-dados-abertos-da-camara-legislativa-...,Portal de Dados Abertos da Câmara Legislativa ...,http://dadosabertos.cl.df.gov.br/,NaN,NaN,NaN,Government,Open Data portal of the local parliament of th...,"local-government,br-DF",NaN,...,"DF, Brazil",NaN,BR,pt,active,2019-09-23T14:22:38Z,NaN,NaN,NaN,NaN
592,stat-uz,The State Committee of the Republic of Uzbekis...,https://stat.uz/en/,Republic of Uzbekistan,The State Committee of the Republic of Uzbekis...,2006-03-23,Government,The official website of the State Committee of...,"statistics,Uzbekistan",cc-by-sa,...,Uzbekistan,"41.316667, 69.266667",UZ,em,active,2020-07-07T14:50Z,NaN,NaN,NaN,https://stat.uz/en/open-data/181-ofytsyalnaia-...
593,data-gov-uz,Open Data Portal of Uzbekistan,https://data.gov.uz/en,Republic of Uzbekistan,The State Committee of the Republic of Uzbekis...,2015-03-30,Government,This is the State information resource on the ...,Uzbekistan,other-at,...,Uzbekistan,"41.316667, 69.266667",UZ,en,active,2020-07-07T14:50Z,NaN,http://data.gov.uz/uz/api/v1/json/dataset?acce...,NaN,NaN

In [15]:
''' Data Preprocessing'''
# Check for missing values in the data using pandas isnull()
df.isnull()

,name,title,url,author,publisher,issued,publisher_classification,description,tags,license_id,...,place,location,country,language,status,metadatacreated,generator,api_endpoint,api_type,full_metadata_download
0,False,False,False,False,False,True,True,False,False,True,...,False,False,False,False,False,False,True,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
2,False,False,False,False,False,True,True,False,False,True,...,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,True,True,True,True,True
4,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,True,True,True,False,True
590,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,True,True,True,True,True
591,False,False,False,True,True,True,False,False,False,True,...,False,True,False,False,False,False,True,True,True,True
592,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,False
593,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,True

In [16]:
# describe() : returns the statistical summary of dataframe or series.
df.describe()

,name,title,url,author,publisher,issued,publisher_classification,description,tags,license_id,...,place,location,country,language,status,metadatacreated,generator,api_endpoint,api_type,full_metadata_download
count,594,594,594,529,533,92,212,544,519,284,...,592,570,579,585,594,452,88,52,80,16
unique,590,588,590,487,496,82,11,540,266,42,...,489,483,125,76,3,416,21,42,20,16
top,state_of_washington,Washington,http://opendata.terrassa.cat/,African Development Bank Group,African Development Bank Group,30/06/2015,Government,Open Data portal of the city of Rio de Janeiro...,canada,cc-by,...,Italy,"0,0",US,en,active,2018-09-12T10:58:52Z,CKAN,Not apparent,Socrata Open Data API (SODA),https://data.qld.gov.au/api/3/action/current_p...
freq,4,4,2,21,22,2,177,2,45,44,...,9,10,100,268,580,30,35,11,27,1

In [19]:
print(df.size) # counts no. of ele along the given axis
print(df.shape) # gives the number of elements in each dimension of an array
print(df.ndim) # return the number of dimensions of an array.

12474
(594, 21)
2

In [21]:
df.dtypes # data types of each col

name                        object
title                       object
url                         object
author                      object
publisher                   object
issued                      object
publisher_classification    object
description                 object
tags                        object
license_id                  object
license_url                 object
place                       object
location                    object
country                     object
language                    object
status                      object
metadatacreated             object
generator                   object
api_endpoint                object
api_type                    object
full_metadata_download      object
dtype: object

In [24]:
dummies=pd.get_dummies(df.author) # return dummy variable colums
merged=pd.concat([df,dummies],axis='columns') # to concatenate dummy columns into df

In [26]:
merged.drop(['author'],axis='columns') # drop column author from dataset

,name,title,url,publisher,issued,publisher_classification,description,tags,license_id,license_url,...,Wyre Council,Xunta de Galicia,data.go.kr,data.gov.sk,e-Government Center,http://g0vhk.io,http://garagelab.tumblr.com/,pinardag,regione sardegna,Örebro Kommun
0,a2gov_org,"Ann Arbor, Michigan",http://www.a2gov.org/services/data/Pages/defau...,City of Ann Arbor,NaN,NaN,City of Ann Arbor's Open Data Catalog (USA),ctic unitedstates,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
1,acikveri-sahinbey-bel-tr,Açık Veri Portali - Test Yayını,http://acikveri.sahinbey.bel.tr/dataset,SahinBey Belediyesi,31/01/2015,Government,The first official open data portal of Turkey,turkey national,Unknown,NaN,...,False,False,False,False,False,False,False,True,False,False
2,africa_open_data,Africa Open Data,http://africaopendata.org/,Africa Open Data,NaN,NaN,Africa's largest central repository for Govern...,ckan africa,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
3,ajuntament-de-tarragona,Open Data Tarragona,http://opendata.tarragona.cat/,Ajuntament de Tarragona,NaN,Government,Open Data Tarragona,city spain,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
4,ajuntament-de-terassa,Open Data Terassa,http://opendata.terrassa.cat/,Ajuntament de Terassa,NaN,Government,Open Data Terassa,city spain,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,state_of_washington,Washington,http://geo.wa.gov,State of Washington,NaN,Government,Geospatial open data from the State of Washington,unitedstates,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
590,state_of_washington,Washington,http://fiscal.wa.gov,State of Washington,NaN,Government,Fiscal open data for state of Washington,finance unitedstates,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
591,portal-de-dados-abertos-da-camara-legislativa-...,Portal de Dados Abertos da Câmara Legislativa ...,http://dadosabertos.cl.df.gov.br/,NaN,NaN,Government,Open Data portal of the local parliament of th...,"local-government,br-DF",NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
592,stat-uz,The State Committee of the Republic of Uzbekis...,https://stat.uz/en/,The State Committee of the Republic of Uzbekis...,2006-03-23,Government,The official website of the State Committee of...,"statistics,Uzbekistan",cc-by-sa,https://creativecommons.org/licenses/by/4.0/,...,False,False,False,False,False,False,False,False,False,False
593,data-gov-uz,Open Data Portal of Uzbekistan,https://data.gov.uz/en,The State Committee of the Republic of Uzbekis...,2015-03-30,Government,This is the State information resource on the ...,Uzbekistan,other-at,https://lex.uz/docs/4277342,...,False,False,False,False,False,False,False,False,False,False